apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-atlassian.fullname" . }}
  labels:
    {{- include "mcp-atlassian.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mcp-atlassian.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if .Values.monitoring.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.service.targetPort }}"
        prometheus.io/path: "/metrics"
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mcp-atlassian.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mcp-atlassian.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if and .Values.secrets .Values.secrets.jiraApiToken }}
            - name: JIRA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "mcp-atlassian.fullname" . }}-secrets
                  key: jira-api-token
            {{- end }}
            {{- if and .Values.secrets .Values.secrets.confluenceApiToken }}
            - name: CONFLUENCE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "mcp-atlassian.fullname" . }}-secrets
                  key: confluence-api-token
            {{- end }}
            {{- if and .Values.secrets .Values.secrets.jiraPersonalToken }}
            - name: JIRA_PERSONAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "mcp-atlassian.fullname" . }}-secrets
                  key: jira-personal-token
            {{- end }}
            {{- if and .Values.secrets .Values.secrets.confluencePersonalToken }}
            - name: CONFLUENCE_PERSONAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "mcp-atlassian.fullname" . }}-secrets
                  key: confluence-personal-token
            {{- end }}
            {{- if and .Values.secrets .Values.secrets.oauth .Values.secrets.oauth.clientId }}
            - name: ATLASSIAN_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "mcp-atlassian.fullname" . }}-secrets
                  key: oauth-client-id
            {{- end }}
            {{- if and .Values.secrets .Values.secrets.oauth .Values.secrets.oauth.clientSecret }}
            - name: ATLASSIAN_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "mcp-atlassian.fullname" . }}-secrets
                  key: oauth-client-secret
            {{- end }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
