{{- if or (and .Values.secrets .Values.secrets.jiraApiToken) (and .Values.secrets .Values.secrets.confluenceApiToken) (and .Values.secrets .Values.secrets.jiraPersonalToken) (and .Values.secrets .Values.secrets.confluencePersonalToken) (and .Values.secrets .Values.secrets.oauth .Values.secrets.oauth.clientId) (and .Values.secrets .Values.secrets.oauth .Values.secrets.oauth.clientSecret) (and .Values.secrets .Values.secrets.oauth .Values.secrets.oauth.accessToken) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-atlassian.fullname" . }}-secrets
  labels:
    {{- include "mcp-atlassian.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.secrets .Values.secrets.jiraApiToken }}
  jira-api-token: {{ .Values.secrets.jiraApiToken | b64enc }}
  {{- end }}
  {{- if and .Values.secrets .Values.secrets.confluenceApiToken }}
  confluence-api-token: {{ .Values.secrets.confluenceApiToken | b64enc }}
  {{- end }}
  {{- if and .Values.secrets .Values.secrets.jiraPersonalToken }}
  jira-personal-token: {{ .Values.secrets.jiraPersonalToken | b64enc }}
  {{- end }}
  {{- if and .Values.secrets .Values.secrets.confluencePersonalToken }}
  confluence-personal-token: {{ .Values.secrets.confluencePersonalToken | b64enc }}
  {{- end }}
  {{- if and .Values.secrets .Values.secrets.oauth .Values.secrets.oauth.clientId }}
  oauth-client-id: {{ .Values.secrets.oauth.clientId | b64enc }}
  {{- end }}
  {{- if and .Values.secrets .Values.secrets.oauth .Values.secrets.oauth.clientSecret }}
  oauth-client-secret: {{ .Values.secrets.oauth.clientSecret | b64enc }}
  {{- end }}
  {{- if and .Values.secrets .Values.secrets.oauth .Values.secrets.oauth.accessToken }}
  oauth-access-token: {{ .Values.secrets.oauth.accessToken | b64enc }}
  {{- end }}
{{- end }}
