{{- if and .Values.persistence.enabled (not .Values.serviceAccount.create) }}
{{- fail "ERROR: When persistence is enabled, serviceAccount.create must be true. ServiceAccount is required for IRSA (IAM Roles for Service Accounts) to access shared storage." }}
{{- end }}
